version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      timeout: 5s

  app1:
    build: .
    container_name: rate-limiter-app1
    ports:
      - "8081:8080"
    depends_on:
      - redis

  app2:
    build: .
    container_name: rate-limiter-app2
    ports:
      - "8082:8080"
    depends_on:
      - redis

  app3:
    build: .
    container_name: rate-limiter-app3
    ports:
      - "8083:8080"
    depends_on:
      - redis

  app4:
    build: .
    container_name: rate-limiter-app4
    ports:
      - "8084:8080"
    depends_on:
      - redis

  app5:
    build: .
    container_name: rate-limiter-app5
    ports:
      - "8085:8080"
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    container_name: nginx-lb
    ports:
      - "80:80"
    volumes:
      - ./src/main/resources/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3
      - app4
      - app5

volumes:
  redis_data:
