version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app1:
    build: .
    container_name: rate-limiter-app1
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8081:8080"

  app2:
    build: .
    container_name: rate-limiter-app2
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8082:8080"

  app3:
    build: .
    container_name: rate-limiter-app3
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8083:8080"

  app4:
    build: .
    container_name: rate-limiter-app4
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8084:8080"

  app5:
    build: .
    container_name: rate-limiter-app5
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8085:8080"

  nginx:
    image: nginx:latest
    container_name: nginx-lb
    ports:
      - "80:80"
    volumes:
      - ./src/main/resources/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3
      - app4
      - app5

volumes:
  redis_data:
